Models/Contexto.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace WebCRUDMVCSQL.Models
{
    public class Contexto : DbContext
    {
        public Contexto(DbContextOptions<Contexto> options) : base(options)
        {
        }

        public DbSet<Produto> Produto { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace CRUD_MVC_DEPLOY.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Produto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebCRUDMVCSQL.Models
{
    [Table("ControledeProdutos")]


    public class Produto
    {
        [Column("Id")]
        [Display(Name = "Código")]
        public int Id { get; set; }

        [Column("Nome")]
        [Display(Name = "Nome")]
        public string? Nome { get; set; }


        [Column("Quantidade")]
        [Display(Name = "Quantidade")]
        public string? Quantidade { get; set; }


        [Column("Preço")]
        [Display(Name = "Preço")]
        public string? Preço { get; set; }
    }
}

Controllers/HomeController.cs
using CRUD_MVC_DEPLOY.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRUD_MVC_DEPLOY.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProdutoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebCRUDMVCSQL.Models;

namespace CRUD_MVC_DEPLOY.Controllers
{
    public class ProdutoesController : Controller
    {
        private readonly Contexto _context;

        public ProdutoesController(Contexto context)
        {
            _context = context;
        }

        // GET: Produtoes
        public async Task<IActionResult> Index()
        {
              return _context.Produto != null ? 
                          View(await _context.Produto.ToListAsync()) :
                          Problem("Entity set 'Contexto.Produto'  is null.");
        }

        // GET: Produtoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Produto == null)
            {
                return NotFound();
            }

            var produto = await _context.Produto
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // GET: Produtoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produtoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Quantidade,Preço")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Produto == null)
            {
                return NotFound();
            }

            var produto = await _context.Produto.FindAsync(id);
            if (produto == null)
            {
                return NotFound();
            }
            return View(produto);
        }

        // POST: Produtoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Quantidade,Preço")] Produto produto)
        {
            if (id != produto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutoExists(produto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Produto == null)
            {
                return NotFound();
            }

            var produto = await _context.Produto
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produtoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Produto == null)
            {
                return Problem("Entity set 'Contexto.Produto'  is null.");
            }
            var produto = await _context.Produto.FindAsync(id);
            if (produto != null)
            {
                _context.Produto.Remove(produto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutoExists(int id)
        {
          return (_context.Produto?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>Controle de estoque</h1>
    <h4>Boas vindas a página inicial do nosso controle de estoque.</h4>
    <p>Preste atenção aos detalhes e confira tudo antes de alterar ou excluir um produto do controle, combinado?</p>
</div>

<div class="text-center">
    <img src="https://i0.wp.com/maino.com.br/wp-content/uploads/2022/09/controle-de-estoque.webp?fit=814%2C596&ssl=1" alt="Controle de Estoque">
</div>

Views/Produtoes/Create.cshtml
@model WebCRUDMVCSQL.Models.Produto

@{
    ViewData["Title"] = "Novo";
}

<h1>Novo Produto</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantidade" class="control-label"></label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preço" class="control-label"></label>
                <input asp-for="Preço" class="form-control" />
                <span asp-validation-for="Preço" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Confirmar Inclusão" class="btn btn-dark" />
            </div>
        </form>
    </div>
</div>
<hr/>
<div>
    <a asp-action="Index" class="btn btn-dark">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Produtoes/Delete.cshtml
@model WebCRUDMVCSQL.Models.Produto

@{
    ViewData["Title"] = "Excluir";
}

<h1>Excluir Produto</h1>

<h3>Você quer mesmo excluuir isso?</h3>
<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preço)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preço)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Confirmar Exclusão" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-dark">Voltar</a>
    </form>
</div>

Views/Produtoes/Details.cshtml
@model WebCRUDMVCSQL.Models.Produto

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes do Produto</h1>

<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preço)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preço)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id"><button type="button" class="btn btn-dark">Alterar</button></a> |
    <a asp-action="Index"><button type="button" class="btn btn-dark">Voltar</button></a>
</div>

Views/Produtoes/Edit.cshtml
@model WebCRUDMVCSQL.Models.Produto

@{
    ViewData["Title"] = "Alterar";
}

<h1>Alterar Produtos</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantidade" class="control-label"></label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preço" class="control-label"></label>
                <input asp-for="Preço" class="form-control" />
                <span asp-validation-for="Preço" class="text-danger"></span>
            </div><br/>
            <div class="form-group">
                <input type="submit" value="Confirmar Alteração" class="btn btn-dark" />
            </div>
        </form>
    </div>
</div><hr/>
<div>
    <a asp-action="Index" class="btn btn-dark">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Produtoes/Index.cshtml
@model IEnumerable<WebCRUDMVCSQL.Models.Produto>

@{
    ViewData["Title"] = "Controle de Estoque";
}

<h1>Controle de estoque</h1>

<p>
    <a asp-action="Create" class="btn btn-dark">Adicionar Produto</a>
</p><hr/>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preço)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preço)
            </td>
            <td>
                    <a asp-action="Edit" class="btn btn-dark" asp-route-id="@item.Id">Alterar</a> |
                    <a asp-action="Details" class="btn btn-dark" asp-route-id="@item.Id">Info</a> |
                    <a asp-action="Delete" class="btn btn-dark" asp-route-id="@item.Id">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Estoque Digital</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD_MVC_DEPLOY.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Estoque Digital</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtoes" asp-action="Index">Controle de Estoque</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Projeto por Gabriella Ramos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>